name: 'NoAI Guardian'
description: 'GitHub Action that audits repo for AI-opt-out protections and recommends fixes to keep your content out of model-training datasets'
author: 'Rahul Rao Natarajan <rahulraonatarajan@gmail.com>'

inputs:
  path:
    description: 'Folder (relative to repo root) to scan'
    required: false
    default: '.'
  fix:
    description: 'Set to true to auto-patch violations'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'

  # Override the image ENTRYPOINT with a shell wrapper
  entrypoint: /bin/sh
  args:
    - -c
    - |
      set -e
      if [ "${{ inputs.fix }}" = "true" ]; then
        python /guard_fix.py --path "${{ inputs.path }}" --fix
      else
        python /guard_fix.py --path "${{ inputs.path }}"
      fi

branding:
  icon: 'shield'
  color: 'blue'
