name: "NoAI Guardian"
description: "GitHub Action that audits HTML/robots.txt for noAI opt-outs, auto-fixes gaps, and keeps your repo out of AI training sets"
author: "rahulraonatarajan"

inputs:
  path:
    description: "Path to the repo folder to scan"
    required: false
    default: "."

  fix:
    description: "Set to true to auto-fix and stage violations"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Run NoAI Guardian
      shell: bash
      run: |
        python3 ${{ github.action_path }}/guard_fix.py \
          --path "${{ inputs.path }}" \
          ${{ inputs.fix == 'true' && '--fix' || '' }}

branding:
  icon: "shield"
  color: "blue"
