name: "NoAI Guardian"
description: "GitHub Action that audits HTML/robots.txt for noAI opt-outs, auto-fixes gaps, and keeps your repo out of AI training sets"
author: "rahulraonatarajan"

inputs:
  path:
    description: "Folder to scan"
    required: false
    default: "."
  fix:
    description: "Set true to auto-fix"
    required: false
    default: "false"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --path
    - ${{ inputs.path }}
    - ${{ inputs.fix == 'true' && '--fix' || '' }}

branding:
  icon: "shield"
  color: "blue"
