name: Self-Test
on: [push]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Call the action from your repo (main branch)
      - uses: rahulrao/noai-guardian-action@main
        with:
          path: '.'
          fix: 'false'      # audit-only
