name: Self-Test
on: [push]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Call the action from your repo (main branch)
      - uses: ./.        # ← dot-slash means “the Action in this repo”
        with:
          path: '.'
          fix: 'false'

